### PR TITLE
Badges

### PR DESCRIPTION
**Pull request by sadathshariff**
Badges

### CODE REVIEW

**Comment by nishasen** [comment]
Everything looks good, you can add some more badges with different sizes maybe.

**Comment by sakleprajwal** [comment]
All good. Go ahead

**Comment by sadathshariff** [comment]
> All good. Go ahead

Thanks Prajwal

**Comment by sadathshariff** [comment]
> Everything looks good, you can add some more badges with different sizes maybe.

Thanks Nisha, will look into that

**Review by sakleprajwal — COMMENTED** [review]
All good. Go ahead

**Pull request merged**
